# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_student_info_universities_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='Recommendation_Letter1',
        ),
        migrations.RemoveField(
            model_name='student_info',
            name='Recommendation_Letter2',
        ),
        migrations.RemoveField(
            model_name='student_info',
            name='Statement_of_Purpose',
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Degree_applying',
            field=models.CharField(default='NO', max_length=500),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Internships',
            field=models.TextField(default='NO'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='List_of_Projects',
            field=models.TextField(default='NO'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Paper_Publications',
            field=models.TextField(default='NO'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='TOEFL_Score',
            field=models.CharField(default='NO', max_length=500),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Universities_Added',
            field=models.TextField(default='NO'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Work_Experience',
            field=models.TextField(default='NO'),
        ),
    ]
