# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_auto_20170729_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_university',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=250)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Degree_applying',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Internships',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='List_of_Projects',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Paper_Publications',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='TOEFL_Score',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Universities_Added',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Work_Experience',
            field=models.TextField(),
        ),
    ]
